" Use Vim settings instead of Vi settings
set nocompatible

" Highlight current line
set cursorline

" Syntax highlighting if the terminal has colors
if &t_Co > 2 || has("gui_running")
    syntax on
endif

" Columns
"set columns=80

" Do not wrap lines
set nowrap

" Indentation
set autoindent
set shiftwidth=4
set smartindent
set tabstop=4
autocmd FileType make setlocal noexpandtab
" Paste as-is
set paste
" Comment out line below when working with makefiles
set expandtab

" Show position of cursor
set ruler

" Command history
set history=50

" Display line numbers
set number

" Backup
set backup
set noswapfile
set undodir=~/.vim/tmp/undo//
set backupdir=~/.vim/tmp/backup//
set directory=~/.vim/tmp/swap//

" Disable error bells
set noerrorbells

" Do not reset cursor to start of line when moving around
set nostartofline
