#!/bin/zsh

# vim dirs
if [ ! -d "$HOME/.vim/tmp/undo" ]
then
	mkdir -p "$HOME/.vim/tmp/undo"
fi
if [ ! -d "$HOME/.vim/tmp/backup" ]
then
	mkdir -p "$HOME/.vim/tmp/backup"
fi
if [ ! -d "$HOME/.vim/tmp/swap" ]
then
	mkdir -p "$HOME/.vim/tmp/swap"
fi

# Profile dirs

if [ -d "$HOME"/.zsh.profile.d ]
then
	for script in `find "$HOME"/.zsh.profile.d/ -type f`
	do
		source "$script"
	done
	for script in `find "$HOME"/.zsh.profile.d/ -type l`
	do
		source "$script"
	done
fi
